// src/components/ImageCYOA.tsx
import { App, checkRequireds, pi, useAppStore } from "@/store";
import { useEffect, useRef, useState } from "react";
import { Button } from "./ui/button";
import {
  Brush,
  CaptionsOff,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  CircleCheckBig,
  ClipboardList,
  Copy,
  FilePlus2,
  List,
  ListTodo,
  Menu,
  PencilRuler,
  Save,
  Trash2,
  Wrench,
} from "lucide-react";
import html2canvas from "html2canvas";
import { cn } from "@/lib/utils";
import Row from "./imageCYOA/Row";
import { useWindowDimensions } from "@/lib/resize";
import Load from "./imageCYOA/storage/Load";
import ActivatedViewer from "./imageCYOA/ActivatedViewer";
import BackpackPreview from "./standardcyoa/BackpackPreview";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "./ui/tooltip";
import { Separator } from "./ui/separator";
import DOMPurify from "dompurify";
import ConfirmDialog from "./imageCYOA/ConfirmDialog";
import RowList from "./RowList";
import Feature from "./imageCYOA/Feature";
import Design from "./imageCYOA/Design";
import IDSearch from "./imageCYOA/features/IDSearch";

export default function ImageCYOA({
  onBack,
  isCreator,
}: {
  onBack: () => void;
  isCreator: boolean;
}) {
  // TODO: implement design component somewhere
  const ref = useRef<HTMLDivElement>(null);
  const bgImage = useAppStore((state) => state.app.styling.backgroundImage);
  const bgColor = useAppStore((state) => state.app.styling.backgroundColor);
  const barBGCol = useAppStore((state) => state.app.styling.barBackgroundColor);
  const barMargin = useAppStore((state) => state.app.styling.barMargin);
  const barPadding = useAppStore((state) => state.app.styling.barPadding);
  const pointTypes = useAppStore((state) => state.app.pointTypes);
  const backpack = useAppStore((state) => state.app.backpack);
  const activated = useAppStore((state) => state.app.activated);
  const barTextColor = useAppStore((state) => state.app.styling.barTextColor);
  const barTextMargin = useAppStore((state) => state.app.styling.barTextMargin);
  const barTextPad = useAppStore((state) => state.app.styling.barTextPadding);
  const barTextFont = useAppStore((state) => state.app.styling.barTextFont);
  const barTextSize = useAppStore((state) => state.app.styling.barTextSize);
  const barPointPos = useAppStore((state) => state.app.styling.barPointPos);
  const barPointNeg = useAppStore((state) => state.app.styling.barPointNeg);
  const rows = useAppStore((state) => state.app.rows);
  const importOpen = useAppStore((state) => state.app.importedChoicesIsOpen);
  const loadApp = useAppStore((state) => state.loadApp);
  const toggleRowEdit = useAppStore((state) => state.toggleRowEdit);
  const cloneRow = useAppStore((state) => state.cloneRow);
  const createNewRow = useAppStore((state) => state.createNewRow);
  const cleanActivated = useAppStore((state) => state.cleanActivated);
  const moveRowUp = useAppStore((state) => state.moveRowUp);
  const moveRowDown = useAppStore((state) => state.moveRowDown);
  const deleteRow = useAppStore((state) => state.deleteRow);
  const [confirmDeleteRow, setConfirmDeleteRow] = useState<
    App["rows"][0] | undefined
  >(undefined);
  const [modal, setModal] = useState<
    | "none"
    | "appLoad"
    | "appActivatedViewer"
    | "appBackpackPreview"
    | "appRowList"
    | "appFeatures"
    | "appDesign"
    | "appIDSearch"
    | "appConfirm"
  >("none");
  const { width } = useWindowDimensions();
  const [topNav, setTopNav] = useState(false);

  async function print() {
    if (!ref.current) return;
    html2canvas(ref.current, {
      imageTimeout: 0,
    }).then(function (canvas) {
      document.body.appendChild(canvas);

      const link = document.createElement("a");
      if (typeof link.download === "string") {
        link.href = canvas.toDataURL();
        link.download = "canvas.png";

        //Firefox requires the link to be in the body
        document.body.appendChild(link);

        //simulate click
        link.click();

        //remove the link when done
        document.body.removeChild(link);
        document.body.removeChild(canvas);
      } else {
        window.open(canvas.toDataURL());
      }
    });
  }

  useEffect(() => {
    /*
    fetch("/project.json")
      .then((r) => r.json())
      .then(loadApp)
      .catch((e) => console.info(`No local project.json found: ${e}`));
      */
  }, [loadApp]);

  const navButtons = [
    {
      text: "New Row",
      component: <FilePlus2 />,
      action: () => createNewRow(),
    },
    {
      text: "Open Row List",
      component: <List />,
      action: () => setModal("appRowList"),
    },
    {
      text: "Open Features",
      component: <PencilRuler />,
      action: () => setModal("appFeatures"),
    },
    {
      text: "Modify Design",
      component: <Brush />,
      action: () => setModal("appDesign"),
    },
    {
      text: "Save/Load Project",
      component: <Save />,
      action: () => setModal("appLoad"),
    },
  ] as const;

  return (
    <div
      className="flex flex-row bg-repeat pb-16 text-center"
      ref={ref}
      style={{
        backgroundImage: `url("${bgImage}")`,
        backgroundColor: bgColor,
      }}
    >
      {isCreator && !topNav && (
        <nav className="fixed z-20 flex h-screen flex-col justify-between bg-white p-2">
          <div className="flex flex-col gap-y-2">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button onClick={() => onBack()} size="icon" variant="ghost">
                    <ChevronLeft />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <span>Return To Menu</span>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <Separator />
            {navButtons.map((button, index) => (
              <TooltipProvider key={index}>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button onClick={button.action} size="icon" variant="ghost">
                      {button.component}
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <span>{button.text}</span>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            ))}
          </div>
          <div className="flex flex-col gap-y-2">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    onClick={() => cleanActivated()}
                    size="icon"
                    variant="ghost"
                  >
                    <CaptionsOff />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <span>Clean Selected Choices</span>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    onClick={() => setModal("appIDSearch")}
                    size="icon"
                    variant="ghost"
                  >
                    <ClipboardList />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <span>See ID/Title List</span>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    onClick={() => setTopNav(true)}
                    size="icon"
                    variant="ghost"
                  >
                    <Menu />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <span>Use Alternate Menu</span>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </nav>
      )}
      <div className={cn(isCreator && !topNav && "ml-14")}>
        {!isCreator && (
          <div
            className="flex flex-row justify-between p-2"
            data-html2canvas-ignore
          >
            <Button
              variant="outline"
              onClick={onBack}
              type="button"
              size="icon"
            >
              <ChevronLeft />
            </Button>
            <div className="flex flex-row gap-x-2">
              <Button onClick={print}>
                Download Image (Go all the way to the bottom to load in the
                pictures first)
              </Button>
              <Button onClick={() => setModal("appLoad")}>Load Project</Button>
            </div>
          </div>
        )}
        {isCreator && topNav && (
          <nav
            className="grid w-full grid-cols-8 justify-evenly gap-4 bg-white px-2.5 py-2.5"
            data-html2canvas-ignore
          >
            <Button onClick={() => onBack()} variant="ghost">
              <ChevronLeft />
            </Button>
            <Button onClick={() => cleanActivated()} variant="ghost">
              De-select Choices
            </Button>
            <Button onClick={() => setTopNav(false)} variant="ghost">
              <Menu />
            </Button>
            {navButtons.map((button, index) => (
              <Button onClick={button.action} variant="ghost" key={index}>
                {button.text}
              </Button>
            ))}
          </nav>
        )}
        {/* Navbar that holds the pointtypes and backpack */}
        {(pointTypes.length > 0 || backpack.length > 0 || importOpen) && (
          <div
            className="fixed bottom-0 left-0 right-0 z-10 flex h-14 flex-row items-center justify-around"
            data-html2canvas-ignore
            style={{
              backgroundColor: barBGCol,
              margin: barMargin + "px",
              padding: barPadding + "px",
            }}
          >
            <div>
              {importOpen && (
                <Button
                  variant="ghost"
                  size="icon"
                  type="button"
                  onClick={() => setModal("appActivatedViewer")}
                >
                  <ListTodo />
                </Button>
              )}
            </div>
            <div className="flex flex-row items-center justify-center">
              {pointTypes
                .filter(
                  (el) =>
                    el.activatedId === "" || activated.includes(el.activatedId),
                )
                .map((score, index) => (
                  <div
                    key={index}
                    style={{
                      color: barTextColor,
                      margin: barTextMargin + "px",
                      padding: barTextPad + "px",
                      fontFamily: `"${barTextFont}"`,
                      fontSize: barTextSize + "px",
                    }}
                  >
                    {score.beforeText}{" "}
                    <span
                      style={{
                        color:
                          pi(score.startingSum) >= 0
                            ? typeof barPointPos !== "undefined"
                              ? barPointPos.hex
                              : ""
                            : typeof barPointNeg !== "undefined"
                              ? barPointNeg.hex
                              : "",
                      }}
                    >
                      {Math.round(pi(score.startingSum))}
                    </span>{" "}
                    {score.afterText}
                  </div>
                ))}
            </div>
            <div>
              {backpack.length > 0 && (
                <Button
                  variant="ghost"
                  size="icon"
                  type="button"
                  onClick={() => setModal("appBackpackPreview")}
                >
                  <CircleCheckBig />
                </Button>
              )}
            </div>
          </div>
        )}
        <Load open={modal === "appLoad"} onClose={() => setModal("none")} />
        <ActivatedViewer
          open={modal === "appActivatedViewer"}
          onClose={() => setModal("none")}
        />
        <BackpackPreview
          open={modal === "appBackpackPreview"}
          onClose={() => setModal("none")}
          type=""
        />
        <ConfirmDialog
          open={modal === "appConfirm"}
          onClose={() => setModal("none")}
          onConfirm={() => {
            if (confirmDeleteRow) {
              deleteRow(confirmDeleteRow);
              setConfirmDeleteRow(undefined);
            }
          }}
          text="Are you sure you want to delete this row?"
        />
        <RowList
          open={modal === "appRowList"}
          onClose={() => setModal("none")}
        />
        <Feature
          open={modal === "appFeatures"}
          onClose={() => setModal("none")}
        />
        <Design open={modal === "appDesign"} onClose={() => setModal("none")} />
        <IDSearch
          open={modal === "appIDSearch"}
          onClose={() => setModal("none")}
        />
        <div
          className={cn(
            "grid grid-cols-2",
            isCreator && !topNav ? "w-[calc(100vw-3.5rem)]" : "w-screen",
          )}
        >
          {/* This is where the rows is shown */}
          {rows.map((row, index) => (
            <div
              key={index}
              className={cn(
                "grid h-max pb-0 pt-0",
                width > 1200 && row.width ? "col-span-1" : "col-span-2",
              )}
            >
              <div>
                {isCreator && (
                  <div className="mx-2 mt-2 flex flex-row items-center justify-between rounded border bg-white px-4 py-4">
                    <div>
                      <b
                        className="text-xl"
                        dangerouslySetInnerHTML={{
                          __html: DOMPurify.sanitize(row.title),
                        }}
                      />
                    </div>
                    <div className="flex flex-row gap-x-2">
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              onClick={() => toggleRowEdit(row)}
                              size="icon"
                              variant="ghost"
                            >
                              <Wrench />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                            <span>Edit Row</span>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              onClick={() => {
                                setConfirmDeleteRow(row);
                                setModal("appConfirm");
                              }}
                              size="icon"
                              variant="ghost"
                            >
                              <Trash2 />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                            <span>Delete Row</span>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              onClick={() => cloneRow(row)}
                              size="icon"
                              variant="ghost"
                            >
                              <Copy />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                            <span>Clone Row</span>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              onClick={() => moveRowUp(row)}
                              size="icon"
                              variant="ghost"
                            >
                              <ChevronUp />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                            <span>Move Row Up</span>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              onClick={() => moveRowDown(row)}
                              size="icon"
                              variant="ghost"
                            >
                              <ChevronDown />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                            <span>Move Row Down</span>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </div>
                  </div>
                )}
                {(isCreator ||
                  checkRequireds({ activated, pointTypes }, row)) && (
                  <Row row={row} type="" isCreator={isCreator} />
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/lib/cyoa/ImageCYOA.svelte
<script lang="ts">
	import { Button, buttonVariants } from '$lib/components/ui/button';
	import { checkRequireds, cleanActivated, loadApp } from '$lib/store/actions';
	import { generateID, pi } from '$lib/store/utils';
	import {
		Brush,
		CaptionsOff,
		ChevronDown,
		ChevronLeft,
		ChevronUp,
		CircleCheckBig,
		ClipboardList,
		Copy,
		FilePlus2,
		List,
		ListTodo,
		Menu,
		PencilRuler,
		Save,
		Trash2,
		Wrench
	} from 'lucide-svelte';
	import { app, appMetaState } from '$lib/store/store.svelte';
	import * as Tooltip from '$lib/components/ui/tooltip';
	import { Separator } from '$lib/components/ui/separator';
	import Load from './storage/Load.svelte';
	import ActivatedViewer from './ActivatedViewer.svelte';
	import BackpackPreview from './BackpackPreview.svelte';
	import ConfirmDialog from './ConfirmDialog.svelte';
	import RowList from './RowList.svelte';
	import Feature from './Feature.svelte';
	import Design from './Design.svelte';
	import IDSearch from './features/IDSearch.svelte';
	import type { App } from '$lib/store/types';
	import { onMount } from 'svelte';
	import { innerWidth } from 'svelte/reactivity/window';
	import Row from './Row.svelte';
	import DOMPurify from 'dompurify';
	import { goto } from '$app/navigation';
	import Filter from './style/Filter.svelte';
	import Background from './style/Background.svelte';
	import MultiChoice from './style/MultiChoice.svelte';
	import ObjectDesign from './style/ObjectDesign.svelte';
	import ObjectImage from './style/ObjectImage.svelte';
	import PointBar from './style/PointBar.svelte';
	import RowDesign from './style/RowDesign.svelte';
	import RowImage from './style/RowImage.svelte';
	import Backpack from './style/Backpack.svelte';
	import Text from './style/Text.svelte';
	import { printDiv } from '$lib/utils';
	import { backgroundImages } from './style/backgroundImageUtils';
	import { getImageURL } from '$lib/store/utils';

	const { isCreator }: { isCreator: boolean } = $props();

	let ref = $state<HTMLDivElement | null>(null);
	let confirmDeleteRow = $state<App['rows'][0] | undefined>(undefined);
	let modal = $state<
		| 'none'
		| 'appLoad'
		| 'appActivatedViewer'
		| 'appBackpackPreview'
		| 'appRowList'
		| 'appFeatures'
		| 'appDesign'
		| 'appIDSearch'
		| 'appConfirm'
	>('none');
	let topNav = $state(false);

	onMount(() => {
		if (app.styling.selFilterBgImages) {
			backgroundImages.set([...app.styling.selFilterBgImages]);
			console.log('Initial backgroundImages in ImageCYOA:', app.styling.selFilterBgImages);
		}
	});

	const navButtons = [
		{
			text: 'New Row',
			component: FilePlus2,
			action: () => {
				const styling = JSON.parse(JSON.stringify($state.snapshot(app.styling)));
				// Removes the images when a new row is created, to stop bloating.
				styling.backgroundImage = '';
				styling.rowBackgroundImage = '';
				styling.objectBackgroundImage = '';
				app.rows.push({
					id: generateID(),
					title: app.defaultRowTitle,
					titleText: app.defaultRowText,
					objectWidth: 'col-md-3',
					image: '',
					template: '1',

					// Button in row.
					isButtonRow: false, // Does the row show an image(true) or an button(false)?
					buttonType: true, // True if permanent, false if switch.
					buttonId: '', // The id of the variable that the button uses.
					buttonText: 'Click',
					buttonRandom: false,
					buttonRandomNumber: 1,

					isResultRow: false, // Is the row a result row?
					resultGroupId: '',
					isInfoRow: false, // Is the row a information row?
					isPrivateStyling: false,

					defaultAspectWidth: 1, // The default width and height for cropper aspect.
					defaultAspectHeight: 1, // The default height for cropper aspect.
					allowedChoices: 0, // Allowed choices in the array.
					currentChoices: 0, // Current selected choices in the array.
					requireds: [],
					isEditModeOn: false,
					isRequirementOpen: false,

					objects: [],
					// Styling is collected like this to make a copy, and not a pointer to the same object.
					styling: styling
				});
			}
		},
		{
			text: 'Open Row List',
			component: List,
			action: () => (modal = 'appRowList')
		},
		{
			text: 'Open Features',
			component: PencilRuler,
			action: () => (modal = 'appFeatures')
		},
		{
			text: 'Modify Design',
			component: Brush,
			action: () => (modal = 'appDesign')
		},
	{
		text: 'Save/Load Project',
		component: Save,
		action: () => {
			console.log('Save/Load Project button clicked');
			modal = 'appLoad';
			console.log('Modal state after click:', modal);
		}
	}
	] as const;

	import { base } from '$app/paths';

	onMount(() => {
		fetch(`${base}/project.json`)
			.then((r) => r.json())
			.then(loadApp)
			.catch((e) => console.info(`No local project.json found: ${e}`));
	});
</script>

<div
	class="flex flex-row pb-16 text-center"  
	bind:this={ref} 
	style:background-image={app.styling.backgroundImage
		? `url("${getImageURL(app.styling.backgroundImage, appMetaState.imagePrefix)}")`
		: null}
	style:background-color={app.styling.backgroundColor}
    style:background-attachment={app.styling.backgroundAttachment ?? 'scroll'}  
    style:background-repeat={app.styling.backgroundRepeat ?? 'no-repeat'}    
    style:background-size={app.styling.backgroundSize ?? 'auto'}                   
>
	{#if isCreator && !topNav}
		<nav class="fixed z-20 flex h-screen flex-col justify-between bg-gray-200 p-2">
			<div class="flex flex-col gap-y-2">
				<Tooltip.Provider>
					<Tooltip.Root>
						<Tooltip.Trigger
							class={buttonVariants({ variant: 'ghost', size: 'icon' })}
							onclick={() => goto('../')}
						>
							<ChevronLeft />
						</Tooltip.Trigger>
						<Tooltip.Content>
							<span>Return To Menu</span>
						</Tooltip.Content>
					</Tooltip.Root>
				</Tooltip.Provider>
				<Separator />
				{#each navButtons as button (button.text)}
					<Tooltip.Provider>
						<Tooltip.Root>
							<Tooltip.Trigger
								class={buttonVariants({ variant: 'ghost', size: 'icon' })}
								onclick={button.action}
							>
								<button.component />
							</Tooltip.Trigger>
							<Tooltip.Content>
								<span>{button.text}</span>
							</Tooltip.Content>
						</Tooltip.Root>
					</Tooltip.Provider>
				{/each}
			</div>
			<div class="flex flex-col gap-y-2">
				<Tooltip.Provider>
					<Tooltip.Root>
						<Tooltip.Trigger
							class={buttonVariants({ variant: 'ghost', size: 'icon' })}
							onclick={cleanActivated}
						>
							<CaptionsOff />
						</Tooltip.Trigger>
						<Tooltip.Content>
							<span>Clean Selected Choices</span>
						</Tooltip.Content>
					</Tooltip.Root>
				</Tooltip.Provider>
				<Tooltip.Provider>
					<Tooltip.Root>
						<Tooltip.Trigger
							class={buttonVariants({ variant: 'ghost', size: 'icon' })}
							onclick={() => (modal = 'appIDSearch')}
						>
							<ClipboardList />
						</Tooltip.Trigger>
						<Tooltip.Content>
							<span>See ID/Title List</span>
						</Tooltip.Content>
					</Tooltip.Root>
				</Tooltip.Provider>
				<Tooltip.Provider>
					<Tooltip.Root>
						<Tooltip.Trigger
							class={buttonVariants({ variant: 'ghost', size: 'icon' })}
							onclick={() => (topNav = true)}
						>
							<Menu />
						</Tooltip.Trigger>
						<Tooltip.Content>
							<span>Use Alternate Menu</span>
						</Tooltip.Content>
					</Tooltip.Root>
				</Tooltip.Provider>
			</div>
		</nav>
	{/if}
	<div class={[isCreator && !topNav && 'ml-14']}>
		{#if !isCreator}
		    <!-- This block should not be displayed in viewer mode. Do not remove this comment - it prevents the Svelte compiler from throwing an empty block error -->
			<!-- @dev-only -->
			<div class="flex flex-row justify-between p-2" data-html2canvas-ignore>
				<Button variant="outline" href="../" size="icon">
					<ChevronLeft />
				</Button>
				<div class="flex flex-row gap-x-2">
					<Button onclick={() => ref && printDiv(ref)}>
						Download Image (Go all the way to the bottom to load in the pictures first)
					</Button>
					<Button onclick={() => (modal = 'appLoad')}>Load Project</Button>
				</div>
			</div>
		{:else if isCreator && topNav}
			<nav
				class="grid w-full grid-cols-8 justify-evenly gap-4 bg-gray-200 px-2.5 py-2.5"
				data-html2canvas-ignore
			>
				<Button href="../" variant="ghost">
					<ChevronLeft />
				</Button>
				<Button onclick={() => cleanActivated()} variant="ghost">De-select Choices</Button>
				<Button onclick={() => (topNav = false)} variant="ghost">
					<Menu />
				</Button>
				{#each navButtons as button (button.text)}
					<Button onclick={button.action} variant="ghost">
						{button.text}
					</Button>
				{/each}
			</nav>
		{/if}

		<div>
			{#if appMetaState.currentDesignComponent === 'appFilter'}
				<Filter
					open={appMetaState.currentDesignComponent === 'appFilter'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appBackground'}
				<Background
					open={appMetaState.currentDesignComponent === 'appBackground'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appMultiChoice'}
				<MultiChoice
					open={appMetaState.currentDesignComponent === 'appMultiChoice'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appObjectDesign'}
				<ObjectDesign
					open={appMetaState.currentDesignComponent === 'appObjectDesign'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appObjectImage'}
				<ObjectImage
					open={appMetaState.currentDesignComponent === 'appObjectImage'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appPointBar'}
				<PointBar
					open={appMetaState.currentDesignComponent === 'appPointBar'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appRowDesign'}
				<RowDesign
					open={appMetaState.currentDesignComponent === 'appRowDesign'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appRowImage'}
				<RowImage
					open={appMetaState.currentDesignComponent === 'appRowImage'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appText'}
				<Text
					open={appMetaState.currentDesignComponent === 'appText'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{:else if appMetaState.currentDesignComponent === 'appBackpack'}
				<Backpack
					open={appMetaState.currentDesignComponent === 'appBackpack'}
					onclose={() => (appMetaState.currentDesignComponent = 'none')}
					embedded={true}
				/>
			{/if}
		</div>

		<!-- Navbar that holds the pointtypes and backpack -->
		{#if app.pointTypes.length > 0 || app.backpack.length > 0 || app.importedChoicesIsOpen}
			<div
				class="fixed bottom-0 left-0 right-0 z-20 flex h-14 flex-row items-center justify-around"
				data-html2canvas-ignore
				style:background-color={app.styling.barBackgroundColor}
				style:margin={app.styling.barMargin + 'px'}
				style:padding={app.styling.barPadding + 'px'}
			>
				<div>
					{#if app.importedChoicesIsOpen}
						<Button
							variant="ghost"
							size="icon"
							type="button"
							onclick={() => (modal = 'appActivatedViewer')}
						>
							<ListTodo />
						</Button>
					{/if}
				</div>
				<div class="flex flex-row items-center justify-center">
					{#each app.pointTypes.filter((el) => el.activatedId === '' || app.activated.includes(el.activatedId)) as score}
						<div
							style:color={app.styling.barTextColor}
							style:margin={app.styling.barTextMargin + 'px'}
							style:padding={app.styling.barTextPadding + 'px'}
							style:font-family={app.styling.barTextFont}
							style:font-size={app.styling.barTextSize + 'px'}
						>
							{score.beforeText}
							<span
								style:color={pi(score.startingSum) >= 0
									? typeof app.styling.barPointPos !== 'undefined'
										? app.styling.barPointPos.hex
										: ''
									: typeof app.styling.barPointNeg !== 'undefined'
										? app.styling.barPointNeg.hex
										: ''}
							>
								{Math.round(pi(score.startingSum))}
							</span>
							{score.afterText}
						</div>
					{/each}
				</div>
				<div>
					{#if app.backpack.length > 0}
						<Button
							variant="ghost"
							size="icon"
							type="button"
							onclick={() => (modal = 'appBackpackPreview')}
						>
							<CircleCheckBig />
						</Button>
					{/if}
				</div>
			</div>
		{/if}
		<Load open={modal === 'appLoad'} onclose={() => (modal = 'none')} />
		<ActivatedViewer open={modal === 'appActivatedViewer'} onclose={() => (modal = 'none')} />
		<BackpackPreview
			open={modal === 'appBackpackPreview'}
			onclose={() => (modal = 'none')}
			type=""
		/>
		<ConfirmDialog
			open={modal === 'appConfirm'}
			onclose={() => (modal = 'none')}
			onconfirm={() => {
				if (confirmDeleteRow) {
					const idx = app.rows.indexOf(confirmDeleteRow);
					app.rows.splice(idx, 1);
					confirmDeleteRow = undefined;
				}
				modal = 'none';
			}}
			text="Are you sure you want to delete this row?"
		/>
		<RowList open={modal === 'appRowList'} onclose={() => (modal = 'none')} />
		<Feature open={modal === 'appFeatures'} onclose={() => (modal = 'none')} />
		<Design open={modal === 'appDesign'} onclose={() => (modal = 'none')} />
		<IDSearch open={modal === 'appIDSearch'} onclose={() => (modal = 'none')} />
		<div class={['grid grid-cols-2', isCreator && !topNav ? 'w-[calc(100vw-3.5rem)]' : 'w-screen']}>
			<!-- This is where the rows is shown -->
			{#each app.rows as row}
				<div
					class={[
						'grid h-max pb-0 pt-0',
						(innerWidth.current ?? 0) > 1200 && row.width ? 'col-span-1' : 'col-span-2'
					]}
				>
					<div>
						{#if isCreator}
							<div
								class="mx-2 mt-2 flex flex-row items-center justify-between rounded border bg-gray-400 px-4 py-4"
							>
								<div>
									<!-- eslint-disable-next-line svelte/no-at-html-tags -->
									<b class="text-xl">{@html DOMPurify.sanitize(row.title)}</b>
								</div>
								<div class="flex flex-row gap-x-2">
									<Tooltip.Provider>
										<Tooltip.Root>
											<Tooltip.Trigger
												class={buttonVariants({ variant: 'ghost', size: 'icon' })}
												onclick={() => (row.isEditModeOn = !row.isEditModeOn)}
											>
												<Wrench />
											</Tooltip.Trigger>
											<Tooltip.Content>
												<span>Edit Row</span>
											</Tooltip.Content>
										</Tooltip.Root>
									</Tooltip.Provider>
									<Tooltip.Provider>
										<Tooltip.Root>
											<Tooltip.Trigger
												class={buttonVariants({ variant: 'ghost', size: 'icon' })}
												onclick={() => {
													confirmDeleteRow = row;
													modal = 'appConfirm';
												}}
											>
												<Trash2 />
											</Tooltip.Trigger>
											<Tooltip.Content>
												<span>Delete Row</span>
											</Tooltip.Content>
										</Tooltip.Root>
									</Tooltip.Provider>
									<Tooltip.Provider>
										<Tooltip.Root>
											<Tooltip.Trigger
												class={buttonVariants({ variant: 'ghost', size: 'icon' })}
												onclick={() => {
													const rowIdx = app.rows.indexOf(row);
													app.rows.splice(
														rowIdx + 1,
														0,
														JSON.parse(JSON.stringify($state.snapshot(row)))
													);
													app.rows[rowIdx + 1].id = generateID();
													for (const object of app.rows[rowIdx + 1].objects) {
														object.id = generateID();
													}
												}}
											>
												<Copy />
											</Tooltip.Trigger>
											<Tooltip.Content>
												<span>Clone Row</span>
											</Tooltip.Content>
										</Tooltip.Root>
									</Tooltip.Provider>
									<Tooltip.Provider>
										<Tooltip.Root>
											<Tooltip.Trigger
												class={buttonVariants({ variant: 'ghost', size: 'icon' })}
												onclick={() => {
													const rowIdx = app.rows.indexOf(row);
													if (rowIdx === 0) return;
													const el = app.rows[rowIdx];
													app.rows[rowIdx] = app.rows[rowIdx - 1];
													app.rows[rowIdx - 1] = el;
												}}
											>
												<ChevronUp />
											</Tooltip.Trigger>
											<Tooltip.Content>
												<span>Move Row Up</span>
											</Tooltip.Content>
										</Tooltip.Root>
									</Tooltip.Provider>
									<Tooltip.Provider>
										<Tooltip.Root>
											<Tooltip.Trigger
												class={buttonVariants({ variant: 'ghost', size: 'icon' })}
												onclick={() => {
													const rowIdx = app.rows.indexOf(row);
													if (rowIdx === app.rows.length - 1) return;
													const el = app.rows[rowIdx];
													app.rows[rowIdx] = app.rows[rowIdx + 1];
													app.rows[rowIdx + 1] = el;
												}}
											>
												<ChevronDown />
											</Tooltip.Trigger>
											<Tooltip.Content>
												<span>Move Row Down</span>
											</Tooltip.Content>
										</Tooltip.Root>
									</Tooltip.Provider>
								</div>
							</div>
						{/if}
						{#if isCreator || checkRequireds(row)}
							<Row {row} type="" {isCreator} />
						{/if}
					</div>
				</div>
			{/each}
		</div>
	</div>
</div>
