// src/lib/cyoa/row/RowSettings.svelte
<script lang="ts">
	import type { Row } from '$lib/store/types';
	import * as Dialog from '$lib/components/ui/dialog';
	import { Button, buttonVariants } from '$lib/components/ui/button';
	import Filter from '../style/Filter.svelte';
	import Text from '../style/Text.svelte';
	import ObjectImage from '../style/ObjectImage.svelte';
	import Background from '../style/Background.svelte';
	import ObjectDesign from '../style/ObjectDesign.svelte';
	import RowDesign from '../style/RowDesign.svelte';
	import RowImage from '../style/RowImage.svelte';
	import WrappedSelect from '$lib/components/wrapped/WrappedSelect.svelte';
	import { app } from '$lib/store/store.svelte';
	import { generateID } from '$lib/store/utils';
	import WrappedInput from '$lib/components/wrapped/WrappedInput.svelte';
	import { Switch } from '$lib/components/ui/switch';
	import { Label } from '$lib/components/ui/label';
	import * as Tooltip from '$lib/components/ui/tooltip';
	import DOMPurify from 'dompurify';

	const { open, onclose, row }: { open: boolean; onclose: () => void; row: Row } = $props();

	let modal = $state<
		| 'none'
		| 'appFilter'
		| 'appText'
		| 'appObjectImage'
		| 'appBackground'
		| 'appObjectDesign'
		| 'appRowDesign'
		| 'appRowImage'
	>('none');

	let sortType = $state<'1' | '2' | '3' | '4'>('1');
	let newRow = $state('');
	const sort = [
		{ name: 'Object Width - Biggest to smallest.', value: '1' },
		{ name: 'Object Width - Smallest to Biggest.', value: '2' },
		{ name: 'Text Length - Longest to Shortest.', value: '3' },
		{ name: 'Text Length - Shortest to Longest.', value: '4' }
	];

	/**
	 * Copies the objects of the row into another row.
	 */
	function mergeRow() {
		for (const row2 of app.rows) {
			if (row2.id === newRow) {
				for (const obj of row.objects) {
					row2.objects.push(JSON.parse(JSON.stringify(obj)));
					row2.objects[row2.objects.length - 1].id = generateID();
				}
			}
		}
	}

	/**
	 * Copies the objects of the row into another row.
	 * And then deletes this row.
	 */
	function mergeAndDeleteRow() {
		for (const row2 of app.rows) {
			if (row.id != newRow && row2.id == newRow) {
				for (const obj of row.objects) {
					row2.objects.push(obj);
				}
				app.rows.splice(app.rows.indexOf(row), 1);
				onclose();
				break;
			}
		}
	}

	function sortRowObjects() {
		const rowObjectWidth = parseInt(row.objectWidth.replace(/\D/g, ''));
		if (sortType == '1') {
			// If the user want to sort the objects after size
			row.objects.sort(function (a, b) {
				let keyA, keyB;
				if (b.objectWidth != '') {
					keyB = parseInt(b.objectWidth.replace(/\D/g, ''));
				} else {
					keyB = rowObjectWidth;
				}
				if (a.objectWidth != '') {
					keyA = parseInt(a.objectWidth.replace(/\D/g, ''));
				} else {
					keyA = rowObjectWidth;
				}
				// Compare the 2 dates
				if (keyA > keyB) return -1;
				if (keyA < keyB) return 1;
				return 0;
			});
		} else if (sortType == '2') {
			// If the user want to sort the objects after reverse size.
			row.objects.sort(function (a, b) {
				let keyA, keyB;
				if (b.objectWidth != '') {
					keyB = parseInt(b.objectWidth.replace(/\D/g, ''));
				} else {
					keyB = rowObjectWidth;
				}
				if (a.objectWidth != '') {
					keyA = parseInt(a.objectWidth.replace(/\D/g, ''));
				} else {
					keyA = rowObjectWidth;
				}
				// Compare the 2 dates
				if (keyA < keyB) return -1;
				if (keyA > keyB) return 1;
				return 0;
			});
		} else if (sortType == '3') {
			// If the user wants to sort the objects after text length.
			row.objects.sort(function (a, b) {
				let keyA = a.text.length;
				let keyB = b.text.length;
				// Compare the 2 dates
				if (keyA > keyB) return -1;
				if (keyA < keyB) return 1;
				return 0;
			});
		} else if (sortType == '4') {
			// If the user
			row.objects.sort(function (a, b) {
				let keyA = a.text.length;
				let keyB = b.text.length;
				// Compare the 2 dates
				if (keyA < keyB) return -1;
				if (keyA > keyB) return 1;
				return 0;
			});
		}
	}

	const buttons = [
		{
			component: 'appFilter',
			text: 'Manage Filter Design',
			tooltip:
				"Here you can change the filters for choices that are selected<br />and the one's you dont have the requirements for."
		},
		{
			component: 'appText',
			text: 'Manage Text Design',
			tooltip: 'Here you can change the size, font and<br />color of the text on titles and text.'
		},
		{
			component: 'appObjectImage',
			text: 'Manage Choices Image Design',
			tooltip: 'Here you can change the margin and padding <br />of images on rows and objects.'
		},
		{
			component: 'appRowImage',
			text: 'Manage Row Image Design',
			tooltip: 'Here you can change the margin and padding <br />of images on rows and objects.'
		},
		{
			component: 'appBackground',
			text: 'Manage Background Design',
			tooltip:
				'Here you can change the color and place images in <br />the background of rows, choices and the whole project.'
		},
		{
			component: 'appRowDesign',
			text: 'Manage Row Design',
			tooltip: 'Here you can change the margin, <br />padding, borders, and drop-shadow on rows.'
		},
		{
			component: 'appObjectDesign',
			text: 'Manage Choice Design',
			tooltip: 'Here you can change the margin, <br />padding, borders, and drop-shadow on choices.'
		}
	] as const;
</script>

<Dialog.Root bind:open={() => open, (a) => !a && onclose()}>
	<Dialog.Content class="sm:max-w-[600px]">
		<Dialog.Header>
			<Dialog.Title>Row Settings</Dialog.Title>
		</Dialog.Header>
		<div class="grid gap-6 py-4">
			<div class="flex flex-col gap-y-2">
				<WrappedSelect
					label="Sort The Choices In The Row"
					items={sort}
					placeholder="Sort By..."
					bind:value={sortType}
				/>
				<Button onclick={() => sortRowObjects()}>Sort</Button>
			</div>
			<div class="flex flex-col gap-y-2">
				<WrappedSelect
					label="Copy Choices Into Another Row"
					items={app.rows.map((r) => ({ name: r.title, value: r.id }))}
					placeholder="Copy this row's objects into..."
					bind:value={newRow}
				/>
				<div class="flex w-full flex-row gap-x-2">
					<Button class="w-full" onclick={() => mergeRow()}>Copy</Button>
					<Button class="w-full" onclick={() => mergeAndDeleteRow()}>Copy and Delete</Button>
				</div>
			</div>
			<div>
				<WrappedSelect
					label="All Choices in Row is Members of This Group"
					items={app.groups.map((g) => ({ name: g.name, value: g.id }))}
					placeholder="All Rows and Objects"
					bind:value={row.resultGroupId}
				/>
			</div>
			{#if app.styling.objectImgObjectFillIsOn || (row.isPrivateStyling && row.styling.objectImgObjectFillIsOn)}
				<div>
					<WrappedInput
						label="Height of the image container"
						type="number"
						suffix="px"
						bind:value={row.styling.objectImgObjectFillHeight}
					/>
				</div>
			{/if}
			<div>
				<div class="flex flex-row items-center gap-x-1">
					<Switch
						id="row-settings-is-private-styling"
						bind:checked={() => row.isPrivateStyling,
						(v) => {
							if (v) {
								row.styling = JSON.parse(JSON.stringify(app.styling));
								row.styling.backgroundImage = '';
							}
							row.isPrivateStyling = v;
						}}
					/>
					<Label for="row-settings-is-private-styling">Use private styling?</Label>
				</div>
			</div>
			{#if row.isPrivateStyling}
				<div class="grid grid-cols-2 gap-2">
					{#each buttons as button}
						<div>
							<Tooltip.Provider>
								<Tooltip.Root>
									<Tooltip.Trigger
										class={[buttonVariants(), 'w-full']}
										onclick={() => (modal = button.component)}
									>
										{button.text}
									</Tooltip.Trigger>
									<Tooltip.Content>
										<span>
											<!-- eslint-disable-next-line svelte/no-at-html-tags -->
											{@html DOMPurify.sanitize(button.tooltip)}
										</span>
									</Tooltip.Content>
								</Tooltip.Root>
							</Tooltip.Provider>
						</div>
					{/each}
				</div>
			{/if}
		</div>
		<Dialog.Footer>
			<Button onclick={() => onclose()}>Close</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>

<Filter open={modal === 'appFilter'} onclose={() => (modal = 'none')} obj={row} from="private" />
<Text open={modal === 'appText'} onclose={() => (modal = 'none')} obj={row} from="private" />
<ObjectImage
	open={modal === 'appObjectImage'}
	onclose={() => (modal = 'none')}
	obj={row}
	from="private"
/>
<Background
	open={modal === 'appBackground'}
	onclose={() => (modal = 'none')}
	obj={row}
	from="private"
/>
<ObjectDesign
	open={modal === 'appObjectDesign'}
	onclose={() => (modal = 'none')}
	obj={row}
	from="private"
/>
<RowDesign
	open={modal === 'appRowDesign'}
	onclose={() => (modal = 'none')}
	obj={row}
	from="private"
/>
<RowImage
	open={modal === 'appRowImage'}
	onclose={() => (modal = 'none')}
	obj={row}
	from="private"
/>

// src/components/imageCYOA/row/RowSettings.tsx
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { App } from "@/store";

export default function RowSettings({
  open,
  onClose,
  row,
}: {
  open: boolean;
  onClose: () => void;
  row: App["rows"][0];
}) {
  void row;
  return (
    <Dialog open={open} onOpenChange={(a) => !a && onClose()}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Edit profile</DialogTitle>
          <DialogDescription>
            Make changes to your profile here. Click save when you're done.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div>Hi</div>
        </div>
        <DialogFooter>
          <Button type="submit">Save changes</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
// <template>
//   <v-dialog v-model="dialog" max-width="600px" @click:outside="cleanCurrentComponent">
//     <v-card>
//       <v-card-title class="headline">Row Settings</v-card-title>
//
//       <v-card-text>
//         <v-container>
//           <v-row>
//             <v-col cols="12">
//               Sort The Choices In The Row
//               <v-select hide-details :items="sort" v-model="sortType" item-text="text" item-value="value" filled
//                 label="Sort By..."></v-select>
//               <v-col class="px-0">
//                 <v-btn @click="sortRowObjects()" style="color: black">Sort</v-btn>
//               </v-col>
//             </v-col>
//
//             <v-col cols="12">
//               Copy Choices Into Another Row
//               <v-select hide-details :items="rows" v-model="newRow" item-text="title" item-value="id" filled
//                 label="Copy this row's objects into..."></v-select>
//               <v-row class="pa-0">
//                 <v-col class="col-md-4 col-sm-12">
//                   <v-btn @click="mergeRow()" style="color: black">Copy</v-btn>
//                 </v-col>
//                 <v-col class="col-md-8 col-sm-12">
//                   <v-btn @click="mergeAndDeleteRow()" style="color: black">Copy and delete</v-btn>
//                 </v-col>
//               </v-row>
//             </v-col>
//             <v-col cols="12">
//               Group Membership
//               <v-select hide-details deletable-chips chips :items="groups" v-model="row.resultGroupId" item-text="name"
//                 item-value="id" filled label="All choices In Row Is Members Of This Group"
//                 placeholder="All Rows and Objects"></v-select>
//             </v-col>
//
//             <v-col cols="12">
//               <v-text-field v-if="
//                 styling.objectImgObjectFillIsOn ||
//                 (row.isPrivateStyling && row.styling.objectImgObjectFillIsOn)
//               " v-model="row.styling.objectImgObjectFillHeight" suffix="px" type="number"
//                 label="Height of the image container" filled hint="Leave empty for no Object-Fit"
//                 persistent-hint></v-text-field>
//             </v-col>
//           </v-row>
//         </v-container>
//
//         <v-container>
//           <v-col>
//             <v-switch class="mt-n2 mb-n6 ms-3" v-model="row.isPrivateStyling"
//               @change="row.styling = JSON.parse(JSON.stringify(styling))" :label="`Use private styling?`"></v-switch>
//           </v-col>
//
//           <v-row v-if="row.isPrivateStyling">
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appFilter'" style="color: black">Manage Filter
//                     Design</v-btn>
//                 </v-col>
//               </template>
//               <span>
//                 Here you can change the filters for choices that are selected
//                 <br />and the one's you dont have the requirements for.
//               </span>
//             </v-tooltip>
//
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appText'" style="color: black">Manage Text Design</v-btn>
//                 </v-col>
//               </template>
//               <span>
//                 Here you can change the size, font and
//                 <br />color of the text on titles and text.
//               </span>
//             </v-tooltip>
//
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appObjectImage'" style="color: black">Manage Choices
//                     Image Design</v-btn>
//                 </v-col>
//               </template>
//               <span>
//                 Here you can change the margin and padding
//                 <br />of images on rows and objects.
//               </span>
//             </v-tooltip>
//
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appRowImage'" style="color: black">Manage Row Image
//                     Design</v-btn>
//                 </v-col>
//               </template>
//               <span>
//                 Here you can change the margin and padding
//                 <br />of images on rows and objects.
//               </span>
//             </v-tooltip>
//
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appBackground'" style="color: black">Manage Background
//                     Design</v-btn>
//                 </v-col>
//               </template>
//               <span>
//                 Here you can change the color and place images in
//                 <br />the background of rows, choices and the whole project.
//               </span>
//             </v-tooltip>
//
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appRowDesign'" style="color: black">Manage Row
//                     Design</v-btn>
//                 </v-col>
//               </template>
//               <span>
//                 Here you can change the margin,
//                 <br />padding, borders, and drop-shadow on rows.
//               </span>
//             </v-tooltip>
//
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appObjectDesign'" style="color: black">Manage Choice
//                     Design</v-btn>
//                 </v-col>
//               </template>
//               <span>
//                 Here you can change the margin,
//                 <br />padding, borders, and drop-shadow on choices.
//               </span>
//             </v-tooltip>
//
//             <v-tooltip right open-delay="1000">
//               <template v-slot:activator="{ on }">
//                 <v-col>
//                   <v-btn v-on="on" @click="currentComponent = 'appBackpack'" style="color: black">Manage Backpack
//                     Design</v-btn>
//                 </v-col>
//               </template>
//               <span>Here you can change the backpack.</span>
//             </v-tooltip>
//           </v-row>
//         </v-container>
//       </v-card-text>
//
//       <component v-bind:is="currentComponent" :from="'private'" :row="row" :currentComponent="currentComponent"
//         @cleanCurrentComponent="currentComponent = $event"></component>
//
//       <v-card-actions>
//         <v-btn color="green darken-1" text @click="cleanCurrentComponent">Close</v-btn>
//       </v-card-actions>
//     </v-card>
//   </v-dialog>
// </template>
//
// <script>
// import Filter from "../style/Filter.vue";
// import Text from "../style/Text.vue";
// import ObjectImage from "../style/ObjectImage.vue";
// import RowImage from "../style/RowImage.vue";
// import Background from "../style/Background.vue";
// import ObjectDesign from "../style/ObjectDesign.vue";
// import RowDesign from "../style/RowDesign.vue";
// import PointBar from "../style/PointBar.vue";
//
// export default {
//   props: {
//     row: Object,
//   },
//   data: function () {
//     return {
//       currentComponent: "",
//       dialog: true,
//       sortType: 1,
//       newRow: "",
//       sort: [
//         { text: "Object Width - Biggest to smallest.", value: "1" },
//         { text: "Object Width - Smallest to Biggest.", value: "2" },
//         { text: "Text Length - Longest to Shortest.", value: "3" },
//         { text: "Text Length - Shortest to Longest.", value: "4" },
//       ],
//       options: [
//         { text: "1", value: "w-100" },
//         { text: "2", value: "w-50" },
//         { text: "3", value: "w-33" },
//         { text: "4", value: "w-25" },
//         { text: "5", value: "w-20" },
//         { text: "6", value: "w-16" },
//         { text: "7", value: "w-14" },
//         { text: "8", value: "w-12" },
//         { text: "9", value: "w-11" },
//         { text: "10", value: "w-10" },
//         { text: "11", value: "w-9" },
//         { text: "12", value: "w-8" },
//       ],
//     };
//   },
//   components: {
//     appFilter: Filter,
//     appText: Text,
//     appObjectImage: ObjectImage,
//     appBackground: Background,
//     appObjectDesign: ObjectDesign,
//     appRowDesign: RowDesign,
//     appPointBar: PointBar,
//     appRowImage: RowImage,
//   },
//   computed: {
//     // Collects styling from Store.
//     styling() {
//       return this.$store.state.app.styling;
//     },
//     // Collects styling from Store.
//     rows() {
//       return this.$store.state.app.rows;
//     },
//     // Collects styling from Store.
//     groups() {
//       return this.$store.state.app.groups;
//     },
//   },
//   methods: {
//     /**
//      * Copies the objects of the row into another row.
//      */
//     mergeRow() {
//       for (var i = 0; i < this.rows.length; i++) {
//         if (this.rows[i].id == this.newRow) {
//           let numOfObjects = this.row.objects.length;
//           for (var x = 0; x < numOfObjects; x++) {
//             this.rows[i].objects.push(
//               JSON.parse(JSON.stringify(this.row.objects[x]))
//             );
//
//             var text = "";
//             var charset = "abcdefghijklmnopqrstuvwxyz0123456789";
//
//             for (var o = 0; o < 4; o++)
//               text += charset.charAt(
//                 Math.floor(Math.random() * charset.length)
//               );
//
//             this.rows[i].objects[this.rows[i].objects.length - 1].id = text;
//           }
//         }
//       }
//     },
//     /**
//      * Copies the objects of the row into another row.
//      * And then deletes this row.
//      */
//     mergeAndDeleteRow() {
//       for (var i = 0; i < this.rows.length; i++) {
//         if (this.row.id != this.newRow && this.rows[i].id == this.newRow) {
//           for (var x = 0; x < this.row.objects.length; x++) {
//             this.rows[i].objects.push(this.row.objects[x]);
//           }
//           this.rows.splice(this.rows.indexOf(this.row), 1);
//           this.cleanCurrentComponent();
//         }
//       }
//     },
//     sortRowObjects() {
//       var rowObjectWidth = parseInt(this.row.objectWidth.replace(/\D/g, ""));
//       if (this.sortType == "1") {
//         // If the user want to sort the objects after size
//         this.row.objects.sort(function (a, b) {
//           var keyA, keyB;
//           if (b.objectWidth != "") {
//             keyB = parseInt(b.objectWidth.replace(/\D/g, ""));
//           } else {
//             keyB = rowObjectWidth;
//           }
//           if (a.objectWidth != "") {
//             keyA = parseInt(a.objectWidth.replace(/\D/g, ""));
//           } else {
//             keyA = rowObjectWidth;
//           }
//           // Compare the 2 dates
//           if (keyA > keyB) return -1;
//           if (keyA < keyB) return 1;
//           return 0;
//         });
//       } else if (this.sortType == "2") {
//         // If the user want to sort the objects after reverse size.
//         this.row.objects.sort(function (a, b) {
//           var keyA, keyB;
//           if (b.objectWidth != "") {
//             keyB = parseInt(b.objectWidth.replace(/\D/g, ""));
//           } else {
//             keyB = rowObjectWidth;
//           }
//           if (a.objectWidth != "") {
//             keyA = parseInt(a.objectWidth.replace(/\D/g, ""));
//           } else {
//             keyA = rowObjectWidth;
//           }
//           // Compare the 2 dates
//           if (keyA < keyB) return -1;
//           if (keyA > keyB) return 1;
//           return 0;
//         });
//       } else if (this.sortType == "3") {
//         // If the user wants to sort the objects after text length.
//         this.row.objects.sort(function (a, b) {
//           var keyA = a.text.length,
//             keyB = b.text.length;
//           // Compare the 2 dates
//           if (keyA > keyB) return -1;
//           if (keyA < keyB) return 1;
//           return 0;
//         });
//       } else if (this.sortType == "4") {
//         // If the user
//         this.row.objects.sort(function (a, b) {
//           var keyA = a.text.length,
//             keyB = b.text.length;
//           // Compare the 2 dates
//           if (keyA < keyB) return -1;
//           if (keyA > keyB) return 1;
//           return 0;
//         });
//       }
//     },
//     cleanCurrentComponent() {
//       this.$emit("cleanCurrentComponent", "");
//     },
//     rowWasChanged() {
//       this.$emit("rowWasChanged", this.row);
//     },
//   },
// };
// </script>
